---
- name: Install base packages {{ basics_packages|join(',') }}
  become: yes
  apt: 
    name: "{{ basics_packages }}"
    state: present

- name: Setup zsh as default shell for {{ user_name }} & root
  become: yes
  user:
    name: "{{ item }}"
    shell: /bin/zsh
    groups: "{{ user_groups }}"
    append: yes
  loop:
    - "{{ user_name }}"
    - root

- name: Create dir for {{ user_name }} systemd services
  file:
    dest: "{{ user_home }}/.config/systemd/user"
    state: directory

- name: Add .profile
  template:
    dest: "{{ user_home }}/"
    src: templates/.profile

- name: Get Z
  git:
    dest: "{{ basics_z_path|dirname }}"
    repo: "{{ basics_z_repo }}"
    depth: 1

- name: Install oh-my-zsh for {{ user_name }}
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh'
    dest: "{{ user_home }}/.oh-my-zsh"
    depth: 1

- name: Install oh-my-zsh for root
  become: yes
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh'
    dest: /root/.oh-my-zsh
    depth: 1

- name: Setup .zshrc for {{ user_name }}
  template:
    dest: "{{ user_home }}"
    src: templates/.zshrc

- name: Setup .zshrc for root
  become: yes
  template:
    dest: /root/
    src: templates/.zshrc
  vars:


- name: Setup .vimrc for {{ user_name }}
  copy:
    dest: "{{ user_home }}"
    src: files/.vimrc

- name: Setup .vimrc for root
  become: yes
  copy:
    dest: /root/
    src: files/.vimrc

- name: Get Base16 colors for xterm
  git:
    dest: "{{ basics_base16_xresources_path }}"
    repo: "{{ basics_base16_xresources_repo }}"
    depth: 1
  when: has_x_server

- name: Setup X resources
  block:
    - slurp:
        src: "{{ basics_base16_xresources_path }}/xresources/base16-{{ basics_base16_scheme }}.Xresources"
      register: basics_base16_colors_encoded
    - template:
        dest: "{{ user_home }}/.Xresources"
        src: templates/.Xresources
      vars:
        basics_base16_colors: "{{ basics_base16_colors_encoded['content'] | b64decode }}"
  when: has_x_server


- name: Add Jo for JSON output
  block:
    - unarchive:
        src: "{{ basics_jo_archive_url }}"
        dest: "{{ user_home }}"
        remote_src: yes
    - command: ./configure
      args:
        chdir: "{{ basics_jo_extract_path }}"
    - command: make check
      args:
        chdir: "{{ basics_jo_extract_path }}"
    - command: make install
      become: yes
      args:
        chdir: "{{ basics_jo_extract_path }}"